name: Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Install ESLint
        run: bun add -d eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin
      
      - name: Create ESLint config if not exists
        run: |
          if [ ! -f .eslintrc.js ]; then
            echo "module.exports = {
              parser: '@typescript-eslint/parser',
              plugins: ['@typescript-eslint'],
              extends: [
                'eslint:recommended',
                'plugin:@typescript-eslint/recommended',
              ],
              rules: {
                '@typescript-eslint/no-explicit-any': 'error',
              },
            };" > .eslintrc.js
          fi
      
      - name: Run ESLint
        run: bunx eslint "**/*.ts"